/**
 * @generated by scripts/update-api-docs.js — DO NOT EDIT
 */
import { z } from 'zod';

export const listApiSpecsInputSchema = {
  category: z
    .enum([
      'search-place',
      'search-geocoding',
      'search-spatial',
      'search-w3w',
      'route-directions',
      'route-optimization',
      'route-map-matching',
      'route-matrix',
    ])
    .optional()
    .describe(
      'Optional category filter. Omit this parameter to search across ALL categories — this is the safest option when unsure. ' +
        'Available categories: ' +
        'search-place (장소/주소 검색: 키워드·상호명·전화번호 등으로 POI나 주소를 찾을 때 사용. 입력 기반 연관 검색어 제안, 좌표·반경 기반 카테고리별 주변 POI 조회, 도로 네트워크 기반 최적 진출입 지점 탐색도 포함. 좌표→주소 변환은 search-geocoding 사용. API 목록: 통합 검색, 다국어 통합 검색, 장소 상세 조회, 시설물 정보 조회, 검색어 추천, 주변 카테고리 검색, 최적 지점 검색), ' +
        'search-geocoding (지오코딩: 주소→좌표 또는 좌표→주소 변환이 목적일 때 사용. 키워드 기반 장소 검색은 search-place 사용. API 목록: 지오코딩, 리버스 지오코딩), ' +
        'search-spatial (공간 검색: 행정구역 경계 폴리곤 조회, 좌표→행정구역 매핑, 좌표계 변환에 사용. 주소 텍스트 변환은 search-geocoding 사용. API 목록: 공간 검색, 행정/법정동 영역 검색, 좌표(계) 변환), ' +
        'search-w3w (what3words: 3단어 주소 체계(what3words) 전용. 일반 주소·좌표 변환은 search-geocoding 사용. API 목록: W3W 검색어 추천, W3W 리버스 지오코딩, W3W 최적 지점 검색), ' +
        'route-directions (경로 탐색: 자동차·도보·PM 실제 경로 좌표와 상세 정보를 반환. 경유지 포함 경로(최대 100개), 출발·도착 예정시간 기반 예측 탐색, 경로 요약 조회가 필요하면 이 카테고리 사용. API 목록: 경로 탐색, 경로 탐색 요약, 경로 예측 탐색, 다중 경유지 탐색 100, 도보/PM 경로 탐색), ' +
        'route-optimization (경유지 방문 순서 최적화: 경로 자체가 아닌 순서 최적화가 목적일 때만 사용. API 목록: TSP(다중 경유지 최적화) 10, TSP(다중 경유지 최적화) 30, TSP(다중 경유지 최적화) 50, TSP(다중 경유지 최적화) 100), ' +
        'route-map-matching (복원: GPS 좌표열을 도로 네트워크에 보정하거나, 속도·각도·시간 등 부가 정보를 활용해 실제 주행 경로를 추론할 때 사용. API 목록: Special Map Matching, MTR 100, MTR 1000), ' +
        'route-matrix (매트릭스: 복수 출발지·도착지 간 거리·시간 요약 정보만 행렬로 반환(경로 좌표 없음). N:1, 1:N, M:N 조합 지원. 1:1 단일 경로나 실제 경로 좌표가 필요하면 route-directions 사용. API 목록: 다중 출발지-단일 목적지, 단일 출발지-다중 목적지, RDM(다중 경로 행렬)).',
    ),
};
